//
// Gender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Gender: String, Codable, CaseIterable {
    case female = "female"
    case male = "male"
    case genderless = "genderless"
    case unknown = "unknown"
}
